### ISSUE TITLE
what is your database?

### ISSUE THREAD

**Issue by bayueqiankong** [amlarraz/MSRF-Net_PyTorch#2]
Can you share your using dataset?
I use the dataset called "Kvasir-SEG",but there is one error:CUDA error: "device-side assert triggered" when process "loss.backward".
![图片](https://user-images.githubusercontent.com/50512206/152309627-7c95ed9f-8c3d-4a86-a6e5-f10b8fc76adc.png)

**Comment by amlarraz** [comment]
Hi @bayueqiankong ,

PyTorch throws this error when there is any problem with the masks values.
The code has been prepared to use masks where each pixel value is the class to which that pixel belongs to. Meaning, if you have 2 classes (as in the Kvasir-SEG dataset, Background and Polyp) each pixel must be 0 (background) or 1 (Polyp). However in Kvasir-SEG the value of the masks are 0 (Background) or 255 (Polyp) so, to use them with this code, first of all, you must to convert the 255 value to 1. Below you can see a simple code to do that using openCV:

```
import os
import cv2

msks_dir = 'You_path_to_masks_folder'
msks_save_dir = 'Folder_to_save_the_new_masks'
msks_list = os.listdir(msks_dir)
for msk_name in msks_list:
    msk = cv2.imread(os.path.join(msks_dir, msk_name),0)
    msk[msk!=0]=1          # all values no zero go to 1
    cv2.imread(os.path.join(msks_save_dir, msk_name.replace('.jpg', '.png'))   # this is to avoid image compression
```

Notice that this is only for binary classification.

However, the original creator of this model has recently released his own code to work with this dataset also in PyTorch. You can see that [here](https://github.com/NoviceMAn-prog/GMSRFNet)

**Comment by bayueqiankong** [comment]
Hi@amlarraz 
Thank you for your advice for my question!you are right.I set n_classes to 2 and mask to refer the code and see that [here](https://github.com/GeorgeBatch/kvasir-seg)
![图片](https://user-images.githubusercontent.com/50512206/152535661-140c03dc-7b83-4f26-90c2-8bd39b5e76ee.png)
By the way,I am looking  forward that your test code is finished.

**Comment by amlarraz** [comment]
Hey!

You can see the test code in [test.py](https://github.com/amlarraz/MSRF-Net_PyTorch/blob/master/test.py) if you want!
